name: Publish Chocolatey
on: workflow_dispatch

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Prepare & Upload to Chocolatey
        run: ./k2s.Tools/Chocolatey/publish.ps1
        shell: pwsh
        env:
          CHOCO_TOKEN: ${{ secrets.CHOCO_TOKEN }}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          CODE_SIGN: ${{ secrets.CODE_SIGN }}
          RELEASE: ${{ github.ref_name}}
          CERTIFICATE:  ${{ secrets.CERTIFICATE }}
