name: Publish GitHub

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['linux', 'windows', 'macOS']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 6.x

      - name: Build
        shell: bash
        run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="k2s-$tag-${{ matrix.target }}"
          # Build everything
          dotnet publish k2s.Cli/k2s.Cli.csproj --framework net6.0 --runtime "${{ matrix.target }}" --self-contained -c Release -o "$release_name"  /property:Version=${tag:1}
          # Pack files
          if [ "${{ matrix.target }}" == "win-x64" ]; then
            # Pack to zip for Windows
            7z a -tzip "${release_name}.zip" "./${release_name}/*"
          else
          tar czvf "${release_name}.tar.gz" "$release_name"
          fi
          # Delete output directory
          rm -rf "$release_name"
          rm -r "k2s.sln"
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: "k2s*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
